project:
  type: website
  output-dir: docs

website:
  title: "Creating Github-hosted Dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - setup.qmd
      - dashboard.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto


